### PR TITLE
TestReport

### PR DESCRIPTION
**Pull request by jawalonoski**
This pull request modifies the TestScript execution engine to return the new TestReport resource rather than the native Crucible format.

There will likely be downstream impacts of merging this pull request with the Crucible web application that will need to be handled.

### CODE REVIEW

**Comment by jawalonoski** [comment]
The engine still needs a few additional operations and assertions to be implemented to fully support the new scripts.

**Comment by jawalonoski** [comment]
This PR is ready to go.

**Comment by arscan** [comment]
@jawalonoski -- i had to make this update so that crucible would get the metadata back in a format that it is expecting. It does not seem to affect list_all, list_testscripts, etc, even though I expected it would.

**Comment by jawalonoski** [comment]
OK, great.

**Pull request merged**
