### PR TITLE
Multiversion

### PR DESCRIPTION
**Pull request by arscan**

### CODE REVIEW

**Comment by arscan** [comment]
@jawalonoski  -- I'm getting an error when doing a validate on a dstu2 StructureDefinition.  Do you know what might be causing this?

```
Error: test_resource_generator_dsut2_StructureDefinition(ResourceGeneratorTest): NoMethodError: private method `binding' called for "http://tools.ietf.org/html/bcp47":String
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/fhir_ext/structure_definition.rb:310:in `check_binding'
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/bootstrap/model.rb:247:in `block (2 levels) in validate_field'
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/bootstrap/model.rb:246:in `each'
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/bootstrap/model.rb:246:in `block in validate_field'
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/bootstrap/model.rb:192:in `each'
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/bootstrap/model.rb:192:in `validate_field'
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/bootstrap/model.rb:148:in `block in validate_profile'
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/bootstrap/model.rb:127:in `each'
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/bootstrap/model.rb:127:in `validate_profile'
/home/travis/build/fhir-crucible/plan_executor/vendor/bundle/ruby/2.2.0/gems/fhir_dstu2_models-1.0.2/lib/fhir_dstu2_models/bootstrap/model.rb:119:in `validate'
/home/travis/build/fhir-crucible/plan_executor/test/unit/resource_generator_test.rb:30:in `run_generator'
/home/travis/build/fhir-crucible/plan_executor/test/unit/resource_generator_test.rb:15:in `block (2 levels) in <class:ResourceGeneratorTest>'
```

**Comment by jawalonoski** [comment]
@arscan I'll investigate

**Comment by jawalonoski** [comment]
The issue is because I override `check_binding` with different arguments in both `StructureDefinition.rb` and `model.rb`... I'll deconflict these...

**Comment by jawalonoski** [comment]
@arscan issued two PR --  fhir-crucible/fhir_models#44 and fhir-crucible/fhir_dstu2_models#6

**Comment by arscan** [comment]
@jawalonoski -- could you give this a once over and try running a few tests before merging?

**Comment by jawalonoski** [comment]
@arscan Yes. Doing it now...

**Pull request merged**
