### PR TITLE
Simple two-server testscript support

### PR DESCRIPTION
**Pull request by mgramigna**
New rake task `execute_multiserver` for executing a testscript on two different FHIR servers. Example multiserver testscript can be found in `lib/tests/testscripts/scripts/spec/testscript-example-multisystem.xml`

Note: Only designed for a testscript with 1 origin and 2 destinations. Functionality of non-multiserver testscripts should be unaffected.

### CODE REVIEW

**Review by tstrass — COMMENTED** [review]
The general multi-server support looks good to me.

The example TestScript fails for me, but that seems to be just because the patient it tries to read doesn't exist. It seems to me a TestScript should never depend on existing resources on the server, but modifying that TestScript is probably out of the scope of this task.

Only other thing I wanted to bring up is a general question for multi-server TestScript handling. Is the only means for comparing behavior of two different servers to perform the same actions and assertions on each in the TestScript? That would lead to a lot of duplication in the TestScript and wouldn't really work if you were to change it to `n` servers instead of two. So I'm just wondering if a slightly different approach might make sense where the multi-server task just runs the TestScript once for each server specified? That way every single-server TestScript can be used as a multi-server one. The advantage to the way it is now is you have the ability to explicitly do different things with each server in the TestScript, but as far as I understand it all we want to do is compare multiple servers to confirm identical behavior. Not sure if I'm missing something.

**Review by tstrass — CHANGES_REQUESTED** [review]
Also when the example TestScript failed, there was no way for me to know which server it failed on without putting in breakpoints, so I think it would be ideal to print the destination server in the error message when a test fails, if possible.

**Comment by mgramigna** [comment]
@tstrass Great points. I'll look into specifying the server the test fails on in the error messages for TestScripts.

As for the more at-large question, this is a good point to bring up. Maybe @okeefm can chime in, but the main use case we're thinking for this is running evaluate measure against two different servers, and comparing those results relative to each other. This might become more clear in the example multiserver evaluate measure script that I'll put up. So it's not so much about running the same exact assertions on two different servers, but rather detecting differences in measure reports generated by evaluating the same measure on two different servers, if that makes sense.

**Comment by okeefm** [comment]
My understanding of the `TestScript` multiserver feature is that you can use it (according to the spec) sort of arbitrarily to do tests that require two or more servers, not necessarily just ones where you want to run identical tests on two servers. I'd prefer to keep that capability, if it doesn't screw things up too much to keep it.

I agree about the error messages, though. The TestScript side of things definitely needs better error reporting.

**Comment by mgramigna** [comment]
@tstrass I pushed up a change that appends the URL of the request to the message for failed assertions

**Comment by okeefm** [comment]
This is what the error message looks like to me. It's a little unclear from this display which server the error was with (since both server URLs are listed here). Is there a better way to display this?

screen shot 2019-02-05 at 2 12 57 pm

**Comment by mgramigna** [comment]
@okeefm After our talk about the URL reporting actually being fine, and this being a more at-large problem with how test reports are shown in `plan_executor`, I added a Jira to our backlog for improving the test reporting messages.

**Review by tstrass — APPROVED** [review]

**Review by okeefm — APPROVED** [review]
Looks good.

**Pull request merged**
