### PR TITLE
Fix test metadata requirements and testscript error.

### PR DESCRIPTION
**Pull request by jawalonoski**
A ran Crucible against a read/create-only server that only supports Patient and Observation.

A number of tests were incorrectly being recommended as "supported only" even though they were not supported.

So, I updated the metadata of those tests.

Also, I fixed a bug with a testscript which was not doing what it claimed it was doing.

### CODE REVIEW

**Comment by kjmahalingam** [comment]
All looks good to me here.

**Comment by jawalonoski** [comment]
Nudge.

**Review by kjmahalingam — APPROVED** [review]
As discussed before, these changes look straightforward and reasonable to me.

**Comment by jawalonoski** [comment]
@arscan

**Comment by jawalonoski** [comment]
@arscan

**Review by arscan — APPROVED** [review]

**Pull request merged**
