### PR TITLE
Fix simple quantity generators.

### PR DESCRIPTION
**Pull request by arscan**
Comparators are not allowed on SimpleQuantity.

```sqty-1: The comparator is not used on a SimpleQuantity (expression : comparator.empty())```
https://www.hl7.org/fhir/STU3/datatypes.html#SimpleQuantity

### CODE REVIEW

**Comment by arscan** [comment]
See https://github.com/fhir-crucible/crucible/issues/298

This fixes all SimpleQuantities in the resource generator.

**Comment by jawalonoski** [comment]
@arscan Your changes look good. I added additional checks for DSTU2. Can you review these?

**Comment by arscan** [comment]
I removed the blanket wiping of comparators for all Quantities, and found a typo.

**Comment by arscan** [comment]
Thanks!

**Pull request merged**
