### PR TITLE
Fix resource generation tests for DeviceRequest, Claim, ClaimResponse.

### LINKED ISSUE #136: X030_DeviceRequest intermittently fails
This can be seen on the Crucible server: https://www.projectcrucible.org/servers/593a8f8e63727513d6020000#5a3af9fe04ebd03841000000/resourcetest_devicerequest/X030_DeviceRequest

This test sometimes fails due to generating an invalid request, the error message (from the FHIR test server) is:
```
DeviceRequest, Element "DeviceRequest.code[x]" (DeviceRequest.code[x]): minimum required = 1, but only found 0
```

When the test is re-run, sometimes a code will be sent, which passes.

Ref: https://github.com/fhir-crucible/plan_executor/blob/master/lib/tests/suites/resource_test.rb#L225

### PR DESCRIPTION
**Pull request by jawalonoski**
Fixes #136

### CODE REVIEW

**Comment by brendankowitz** [comment]
:shipit:

**Comment by arscan** [comment]
Thanks for the kick -- these PRs slipped through the cracks.  I'll review and get them in shortly.

**Comment by jawalonoski** [comment]
@arscan

**Comment by arscan** [comment]
Alright, clearing out the backlog here.  Looks good.

**Pull request merged**
