### PR TITLE
Implement basic funcitonality for testscript resources

### PR DESCRIPTION
**Pull request by arscan**
Many assertions types and some operations are not yet implemented; see Pivotal.  But this gets the basics working.

Example: `bundle exec rake crucible:execute[https://sqlonfhir-dstu2.azurewebsites.net/fhir,ReadTestScript]`

Also should work for `HistoryTestScript`, `SearchTestScript`, `ExampleTestScript`, `UpdateTestScript`.  By "work" I mean not break hard... not all the tests pass because some scripts do wierd things like Conditional Create which is not implemented yet in this.

Works fine running through crucible for me as well -- look for test suite names starting with _TS_

### CODE REVIEW

**Comment by arscan** [comment]
I'm having trouble figuring out where `pull_out_id` is being defined so I can see what it does @jawalonoski.  All that `id_from_path` does is pull out "exampleid" from "#exampleid".  It is extremely un-robust because it needs to be reworked to support grabbing resources from fhir servers & fixtures anyhow.

**Comment by jawalonoski** [comment]
`pull_out_id` is defined in `fhir_client/lib/resource_address.rb`

**Comment by arscan** [comment]
So it looks like `pull_out_id` will take a string like "FHIR::Fixture/fixtureid" and pull out "fixtureid".  Should I restructure the references to be in that format so I can use it, or should I continue using "#fixtureid" as the format as we originally discussed?  You have more perspective than me.

**Comment by jawalonoski** [comment]
Something like

``` ruby
def id_from_path(resource_type,path)
  if path.start_with?('#') # local reference to contained resource
    path[1..-1] 
  else # full or partial URL
    FHIR::ResourceAddress.pull_out_id(resource_type,path)
  end
end
```

**Comment by arscan** [comment]
Ugh, sorry, I got this wrong.  The purpose of this function is to translate "/id1" into "id1", not "#id1" into "id1".  Sorry for the confusion... there is a different function that does the "#" work (which is a bit more robust), which I what I got this mixed up with.

So here's what it is trying to do. I have xml like this:

``` xml
      <operation>
        <type>
          <code value="read"/>
        </type>
        <resource value="Patient"/>
        <params value="/3141592unlikely"/>
      </operation>
```

And I want to grab `3141592unlikely` out of it.

So I could do something like 

``` ruby

FHIR::ResourceAddress.pull_out_id("FHIR::#{operation.resource}".constantize, "FHIR::#{operation.resource}#{operation.params}"

```

(but in more steps so it isn't impossible to understand, but that is how it would essentially work)

But it seems like I'm doing a lot of massaging to get it into a format that `pull_out_id` can use, which is essentially just stripping off the "/".  What else could that `<params>` value hold beside an id that starts with a "/"?

**Comment by jawalonoski** [comment]
Nevermind. I'm going to merge this and we'll sort it out later.

**Pull request merged**
